### PR TITLE
fix(typed): Return a function operating independently of type system

### LINKED ISSUE #141: Cannot merge typed functions with simple type system
Consider
```
typed.types = [
  { name: 'number',    test: x => typeof x === 'number' },
  { name: 'string',    test: x => typeof x === 'string' }
]

const vanilla = typed({number: n => n+2})
console.log('Vanilla', vanilla(2))

const sprinkles = typed(vanilla, {string: s => s + ' two'})
console.log('With sprinkles', sprinkles('cookie'), sprinkles(3))
```
Looks perfectly innocuous, yet it fails with `TypeError: Unknown type "Object"`.
Somehow, the infrastructure should not crumble because the the client just wants a few types...

### PR DESCRIPTION
**Pull request by gwhitney**
Prior to this commit, the typed object was itself a typed-function,
  which meant that if the client completely replaced the type system,
  `typed()` would no longer be able to supply sensible error messages.

  This commit makes the typed object a plain function (sorry, no
  more dogfooding here, unfortunately) and uses the resulting flexibility
  to allow arbitrary merges of any collection of typed functions, plain
  functions with a signature property, or objects mapping signatures to
  functions. Thus, there is no longer any artificial distinction between
  "creating" and "merging" typed functions -- one can simply specify the
  implementations for any collection of signatures in any of the available
  ways.

  Resolves #141.

### CODE REVIEW

File: typed-function.js [hunk 1]
```diff
@@ -1259,96 +1259,137 @@
...
+     * string-valued name argument if present, or if not, by the name
+     * of any of the arguments that have one, as long as any that do are
+     * consistent with each other. If no name is specified, the name will be
+     * an empty string.
+     *
+     * @param {string} name [optional]
+     * @param {(function|object)[]} signature providers
+     * @returns {typed-function}
+     */
+    typed = function(maybeName) {
```
Comment (josdejong) [inline typed-function.js:1347]: I'm not sure what all different browser do with the name of this unnamed function, but maybe you can just change it from `typed = function() {...}` to `function typed() {...}`?

File: typed-function.js [hunk 2]
```diff
@@ -1259,96 +1259,137 @@
...
+      const named = typeof maybeName === 'string'
+      let name = named ? maybeName : ''
+      let start = named ? 1 : 0
+      let allSignatures = {}
+      for (let i = start; i < arguments.length; ++i) {
```
Comment (josdejong) [inline typed-function.js:1352]: This for-loop is quite large and has quite some nesting. At first sight it looks complex. Open question: are there ways to make this function smaller? Some ideas:

- extract checks into util functions like `isPlainObject`, `isTypedFunction`, `isFunctionWithSignature` and use them here.
- flatten the cases 1, 2, 3, and only have one error handling case at the end (instead of the current two)

File: typed-function.js [hunk 3]
```diff
@@ -1259,96 +1259,137 @@
...
+          throw err
+        }
+        /* Item is ok and we have the signatures and maybe a name */
+        if (!named) {
+          name = checkName(name, thisName)
+        }
+        mergeSignatures(allSignatures, theseSignatures)
       }
-    });
+      return createTypedFunction(name || '', allSignatures)
```
Comment (josdejong) [inline typed-function.js:1387]: I'm not sure about setting the default name to an empty string `''`, is that indeed needed? Or does it make sense to leave it undefined, and handle the undefined case when it occurs?

**Review by josdejong — CHANGES_REQUESTED** [review]
This is really neat 😎 , it makes the `typed` function much more flexible, and solves these issues where you tried to tried to merge new signatures into a typed-function via `typed(typedFn, object)`, which wasn't supported.

I do like getting rid of using typed-function itself in creating itself. It's indeed nice eat-your-own-dog-food, but it can be frustrating at times when you try to fix/refactor/change something and typed-function _itself_ cannot be constructed.

File: typed-function.js (hunk 1 above)
Comment (gwhitney) [reply typed-function.js:1347]: I will try this and see if it works the same way; my main concern was whether you can "replace" an existing variable with a classic-style function definition. Will let you know how it goes.

File: typed-function.js (hunk 2 above)
Comment (gwhitney) [reply typed-function.js:1352]: Yeah, I thought you might be concerned about the number of lines of code in this function. I will try to streamline/factor it, thanks for the suggestions about possible tactics for it.

File: typed-function.js (hunk 3 above)
Comment (gwhitney) [reply typed-function.js:1387]: Well, I originally had just `name` there, but the unit tests assert that all unnamed typed functions have precisely the name `''` so for them to pass I had to change it to this expression `name | ''`. Let me know if you'd rather I change the tests to match the behavior without the `|| ''`, or leave things as they are now.

File: typed-function.js (hunk 1 above)
Comment (gwhitney) [reply typed-function.js:1347]: Yeah, if one makes this change, at the very first call to typed() in a test, JavaScript throws a `TypeError: typed is not a function` error. So I think that since typed is first a temporary non-function object, there's no choice but to reassign it with an anonymous function, and it seems to work. If it fails a particular browser let me know and maybe we can define a named function with a different name and assign that to typed and then change the name property of that new function to 'typed' but that seems more convoluted if an anonymous function works.

File: typed-function.js (hunk 2 above)
Comment (gwhitney) [reply typed-function.js:1352]: OK, how's the version I just committed? Once some version of #135 is merged, I can change case 2 to use isTypedFunction; I didn't want to make this PR and that one overlap in a way that might make merging/rebasing tricky.

File: typed-function.js (hunk 1 above)
Comment (josdejong) [reply typed-function.js:1347]: >  So I think that since typed is first a temporary non-function object, there's no choice but to reassign it

Ah, yes I understand. Ok let's leave it like this. It would be nice to see if we can get rid of this temporary non-function object somehow, but better to try that in a future PR.

File: typed-function.js (hunk 3 above)
Comment (josdejong) [reply typed-function.js:1387]: Ah ok, makes sense to keep it like this then 👍 .

File: typed-function.js (hunk 2 above)
Comment (josdejong) [reply typed-function.js:1352]: Nice, thanks! I like the result, it is easier to follow now 👍

**Review by josdejong — APPROVED** [review]
Thanks for the updates Glen, looks good!
